"""Generate manuscript/NUMBERS.md — the canonical value for every quantity the
manuscript reports, read straight from results/.

Written because the project has three defensible aggregations of the same eight
cells (5-seed mean, bootstrap median, single seed) and they differ by 1-3 points.
Quoting whichever one is nearest to hand is how §02 and §07 of the write-up ended
up stating MIMIC race synergy as 36.9 and 24.3 in the same document.

**Convention, decided 2026-09-01:**

    point estimate  =  mean over the 5 k-means seeds   (headline_matched_panel12)
    interval        =  95% patient bootstrap CI        (bootstrap_ci_matched_panel12)
    floor           =  conditional-independence null   (pid_null_calibration)

The floor is measured on the same 5 seeds, so `debiased = point - floor` is a
like-for-like subtraction. Bootstrap medians are NOT point estimates here: the
resamples refit the codebook, so the median sits 1-3 points off the seed mean.

    PYTHONPATH=src .venv/bin/python src/manuscript_numbers.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "results"
ATOMS = ("red", "u_val", "u_str", "syn")
NICE = {"red": "redundant", "u_val": "unique-to-value",
        "u_str": "unique-to-structure", "syn": "synergistic"}
TARGET_NICE = {"mortality": "mortality", "hospital_expire_flag": "mortality",
               "race_binary": "race", "gender_female": "sex", "age_ge65": "age >=65"}


def load(name):
    return json.loads((R / name).read_text())


def main():
    head = load("headline_matched_panel12.json")
    boot = load("bootstrap_ci_matched_panel12.json")
    cal = load("pid_null_calibration.json")
    gate = load("ijoint_gate_summary.json")
    comp = load("composition_across_db_and_outcome.json")
    ksw = load("k_resolution_headline_impact.json")
    wh = load("eicu_within_hospital.json")
    dose = load("pooling_dose_response.json")

    H = {(c["db"], c["target"]): c for c in head["cells"] if c["measure"] == "broja"}
    C = {(c["db"], c["target"]): c for c in cal["cells"] if c["measure"] == "broja"}
    G = {(c["dataset"], TARGET_NICE.get(c["target"], c["target"])): c for c in gate["cells"]}
    order = [(db, t) for db in ("MIMIC-IV", "eICU-CRD")
             for t in ("mortality", "race_binary", "gender_female", "age_ge65")]

    L = []
    w = L.append
    w("# Manuscript numbers\n")
    w("Generated by `src/manuscript_numbers.py` from `results/`. Do not hand-edit —\n"
      "regenerate. Every figure below is the canonical value under the aggregation\n"
      "convention fixed on 2026-09-01.\n")
    w("## Convention\n")
    w("| quantity | source | file |")
    w("|---|---|---|")
    w("| point estimate | mean over 5 k-means seeds | `headline_matched_panel12.json` |")
    w("| interval | 95% patient bootstrap CI, codebook refit per replicate | `bootstrap_ci_matched_panel12.json` |")
    w("| floor | conditional-independence null, same 5 seeds | `pid_null_calibration.json` |")
    w("\nBootstrap medians are **not** point estimates: the resamples refit the codebook, so\n"
      "the median sits 1–3 points off the seed mean. Use the CI for precision, the seed\n"
      "mean for the value.\n")

    p = head["protocol"]
    w(f"\n**Protocol.** k={p['k']}, {p['grid']} grid, matched 12-analyte panel "
      f"(24-d channels both databases), BROJA primary / CCS sensitivity, seeds {p['seeds']}. "
      f"`collapse_for_occupancy` is not applied anywhere.\n")

    w("\n## 1. Cohorts\n")
    w("| database | n | mortality prevalence |")
    w("|---|---|---|")
    for db in ("MIMIC-IV", "eICU-CRD"):
        c = H[(db, "mortality")]
        w(f"| {db} | {c['n']:,} | {c['prevalence']:.4f} |")

    w("\n## 2. Significance gate on I(Y;V,S)\n")
    w(f"`{gate['protocol']['grid']}`, {gate['protocol']['n_perm']} permutations, "
      f"budget {gate['protocol']['budget_s']:.0f}s.\n")
    w("| database | outcome | n | I_joint | null mean | ratio | p | draws used |")
    w("|---|---|---|---|---|---|---|---|")
    for db, t in order:
        g = G.get((db, TARGET_NICE[t]))
        if not g:
            continue
        drop = g.get("n_perm_dropped", 0)
        used = g.get("n_perm_effective", g.get("n_perm_used"))
        w(f"| {db} | {TARGET_NICE[t]} | {g['n']:,} | {g['I_joint_obs']:.5f} | "
          f"{g['I_joint_null_mean']:.5f} | {g['I_joint_obs']/g['I_joint_null_mean']:.0f}x | "
          f"{g['I_joint_p']:.4f} | {used}{f' (−{drop})' if drop else ''} |")
    rat = [g["I_joint_obs"] / g["I_joint_null_mean"] for g in gate["cells"]]
    w(f"\nAll {len(gate['cells'])} cells clear the gate; ratios span "
      f"**{min(rat):.0f}x to {max(rat):.0f}x**.\n")

    w("\n## 3. Composition — point estimate, interval, floor, net\n")
    w("Percent of each cell's joint information, BROJA.\n")
    w("> The conditional-independence null forces the TRUE `u_str` and `syn` to zero, so\n"
      "> what the estimator reports for those two is bias and can be subtracted. It does\n"
      "> **not** zero `red` or `u_val` — under that null V still carries all the\n"
      "> information, so their null values (~92% for `u_val`) are the null's own\n"
      "> composition, not a floor. Never subtract them.\n")
    w("| database | outcome | atom | 5-seed mean ± sd | bootstrap 95% CI | null floor | net of floor |")
    w("|---|---|---|---|---|---|---|")
    DEBIASABLE = ("u_str", "syn")
    for db, t in order:
        h, c = H[(db, t)], C.get((db, t))
        b = boot["cells"].get(f"{db}/{'mortality' if t=='mortality' else t}", {}).get("measures", {}).get("broja", {})
        for a in ATOMS:
            ci = b.get(a, {}).get("ci95")
            ci_s = f"[{ci[0]:.2f}, {ci[1]:.2f}]" if ci else "—"
            if a in DEBIASABLE and c:
                fl = c[f"null_{a}_mean"]
                fl_s, net_s = f"{fl:+.3f}", f"{h[f'{a}_mean'] - fl:.2f}"
            else:
                fl_s, net_s = "n/a", "n/a"
            w(f"| {db} | {TARGET_NICE[t]} | {NICE[a]} | {h[f'{a}_mean']:.2f} ± {h[f'{a}_sd']:.2f} | "
              f"{ci_s} | {fl_s} | {net_s} |")

    w("\n## 4. Estimator calibration\n")
    b_cells = [c for c in cal["cells"] if c["measure"] == "broja"]
    c_cells = [c for c in cal["cells"] if c["measure"] == "ccs"]
    w(f"- BROJA unique-to-structure is unbiased: max |null mean| = "
      f"**{max(abs(c['null_u_str_mean']) for c in b_cells):.5f}** across all "
      f"{len(b_cells)} cells.")
    w(f"- CCS unique-to-structure is miscalibrated: null means span "
      f"**{min(c['null_u_str_mean'] for c in c_cells):.2f} to "
      f"{max(c['null_u_str_mean'] for c in c_cells):.2f}** — not usable.")
    w(f"- Synergy carries a floor of **{min(c['null_syn_mean'] for c in cal['cells']):.1f} to "
      f"{max(c['null_syn_mean'] for c in cal['cells']):.1f}** points; net of it, synergy spans "
      f"{min(c['debiased_syn'] for c in cal['cells']):.1f} to "
      f"{max(c['debiased_syn'] for c in cal['cells']):.1f}.")

    w("\n## 5. Resolution\n")
    fx = [r for r in ksw["sweep"] if r["arm"] == "fixed"]
    w("Seed spread (worst atom sd) against k, fixed grid:\n")
    ks = sorted({r["k"] for r in fx})
    w("| k | " + " | ".join(str(k) for k in ks) + " |")
    w("|---|" + "---|" * len(ks))
    for db in ("MIMIC-IV", "eICU-CRD"):
        row = {r["k"]: r["worst_sd"] for r in fx if r["db"] == db}
        w(f"| {db} | " + " | ".join(f"{row[k]:.2f}" for k in ks) + " |")
    deg = ksw["why_k13"]["degeneracy_above_k13"]
    if deg:
        w("\nSolver degeneracy above k=13: " + "; ".join(
            f"{d['db']} k={d['k']} — {d['n_seeds_failed']}/5 seeds fail, "
            f"{d['mean_empty_cells']:.1f} empty cells" for d in deg) + ".")
    cv = ksw["collapse_verdict"]
    w(f"\nCollapse: diverges from k={cv['first_k_diverging_by_1pt_synergy']}; at k>=13 it shifts "
      f"unique-to-value by {cv['mean_u_val_shift_at_k_ge_13']:+.1f} and synergy by "
      f"{cv['mean_syn_shift_at_k_ge_13']:+.1f} points, and widens seed spread in "
      f"{cv['n_combinations_where_collapse_has_larger_seed_spread']}/"
      f"{cv['n_combinations_total']} (db,k) combinations.")

    w("\n## 6. Variance decomposition\n")
    vd = comp["variance_decomposition_pct_of_total"]
    w("| atom | database | outcome | interaction | seed noise |")
    w("|---|---|---|---|---|")
    for a in ATOMS:
        v = vd[a]
        w(f"| {NICE[a]} | {v['database']} | {v['outcome']} | {v['interaction']} | {v['seed_noise']} |")

    w("\n## 7. Pooling\n")
    w("Within-hospital vs size-matched random draw, eICU, k=5 (not comparable to k=13):\n")
    w("| outcome | u_str within | u_str random | Δ |")
    w("|---|---|---|---|")
    for r in sorted(wh["pooling_effect"], key=lambda r: -r["delta_u_str"]):
        w(f"| {TARGET_NICE.get(r['target'], r['target'])} | {r['within_u_str']:.2f} | "
          f"{r['random_u_str']:.2f} | {r['delta_u_str']:+.2f} |")
    w("\nDose-response, total n fixed at 3,000, k=5:\n")
    w("| outcome | slope/doubling | p | verdict across truncations |")
    w("|---|---|---|---|")
    sens = {}
    for s in dose.get("truncation_sensitivity", []):
        sens.setdefault(s["target"], []).append(s)
    for t, d_ in dose["dose_response_u_str"].items():
        if not isinstance(d_, dict) or "slope_per_doubling" not in d_:
            continue
        ss = sens.get(t, [])
        sig = [x for x in ss if x["slope_p"] < 0.05]
        verdict = ("robust — significant at every truncation" if ss and len(sig) == len(ss)
                   else "no trend at any truncation" if not sig
                   else f"unstable — significant in {len(sig)}/{len(ss)} truncations")
        w(f"| {TARGET_NICE.get(t, t)} | {d_['slope_per_doubling']:+.3f} | "
          f"{d_['slope_p']:.2e} | {verdict} |")

    out = ROOT / "manuscript" / "NUMBERS.md"
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out}  ({len(L)} lines)")


if __name__ == "__main__":
    main()
